### PR TITLE
More robust last pk handling

### PR DESCRIPTION
**Pull request by pydanny**
Fixed this test from https://github.com/AnswerDotAI/fasthtml/issues/550:

```
from fasthtml.common import *

db = database(':memory:')
streets = db.t.streets

s = streets.lookup({'name': 'test3'})
print(s)
```

### CODE REVIEW

**Comment by jph00** [comment]
Maybe should be `data['_rowid_']` as a backup option, instead of `data['id']`?

**Comment by pydanny** [comment]
In my examinations, the `dict` doesn't include a `_rowid_`, however, `id` always exists. Therefore I have provided `_rowid_` as the first backup option.

Am looking into how to ensure that `_rowid_` is consistently returned.

**Comment by jph00** [comment]
I’d like to understand exactly what’s going on. Why is “id” always available? Normally in SQLite there is always a rowid.

**Comment by pydanny** [comment]
I'm a bit stuck, the flow of the code is here. Trying to figure out where a transformation might be happening.

```python
flowchart TD
    fl.lookup -->|_orig_lookup| sm.lookup --> fl.insert
    fl.insert -->|_orig_insert| sm.insert --> fl.insert_all
    fl.insert_all -->|_orig_insert_all| sm.insert_all
```

**Pull request closed without merging**
